import test from 'node:test';
import assert from 'node:assert/strict';
import {ARSENAL_ITEMS,ARSENAL_RECIPES,arsenalStats,inThrust,castArsenal} from '../public/arsenal.mjs';
import {eligibleItems,eligibleRecipes,chestRewards} from '../public/rules.mjs';
import {calculateStats} from '../public/stats.mjs';
import {CHARACTERS} from '../public/characters.mjs';
import {CoopWorld,coopEligible} from '../public/coop-model.mjs';
const stats=calculateStats(CHARACTERS.knight);
test('each new transformation requires weapon VIII, keeps passive and excludes consumed base',()=>{for(const r of ARSENAL_RECIPES){const inv={...r.requires},base=r.consume[0];assert(eligibleRecipes(inv).some(q=>q.id===r.id));assert(!eligibleRecipes({...inv,[base]:7}).some(q=>q.id===r.id));const result=chestRewards(inv,()=>0,[],r.id);assert(result.inventory[r.id]);assert(!result.inventory[base]);assert(!eligibleItems(result.inventory).includes(base));for(const [id] of Object.entries(r.requires))if(id!==base)assert.equal(result.inventory[id],inv[id]);}});
test('level VIII has a damage spike and Echo amplifies all three families',()=>{for(const id of ['halberd','bell','tome']){const a=arsenalStats(id,7,stats),b=arsenalStats(id,8,stats),echo=arsenalStats(id,8,{...stats,amount:6});assert(b.damage>a.damage*1.35);assert((echo.count||echo.jumps)>(b.count||b.jumps));}});
test('halberd thrust is directional and reaches farther than its width',()=>{assert(inThrust({x:0,y:0},{x:180,y:10},0,200,20));assert(!inThrust({x:0,y:0},{x:-30,y:0},0,200,20));assert(!inThrust({x:0,y:0},{x:100,y:70},0,200,20));});
function cast(inv,targets,clear=()=>true){const hits=[],effects=[],pools=[],cool={};castArsenal({inv,cool,stats,position:{x:0,y:0},facing:0,targets,point:e=>e,dead:e=>false,radius:()=>10,damage:(e,n)=>hits.push({id:e.id,damage:n}),effect:e=>effects.push(e),pool:e=>pools.push(e),clear});return {hits,effects,pools,cool};}
test('lightning chains distinct targets and walls block new attacks',()=>{const targets=[{id:1,x:80,y:0},{id:2,x:200,y:0},{id:3,x:320,y:0}];const c=cast({bell:4},targets);assert.deepEqual(c.hits.map(h=>h.id),[1,2,3]);assert.equal(c.effects.length,3);for(const id of ['halberd','bell','tome'])assert.equal(cast({[id]:8},targets,()=>false).hits.length,0);});
test('Ashen Covenant creates damaging fire pools and Crown attacks around the player',()=>{const targets=[{id:1,x:80,y:0},{id:2,x:-80,y:0}];const c=cast({covenant:1},targets);assert.equal(c.pools.length,2);assert(c.pools.every(p=>p.kind==='fire'&&p.duration>0&&p.damage>0));const h=cast({reckoning:1},targets);assert(h.hits.some(h=>h.id===1));assert(h.hits.some(h=>h.id===2));});
test('co-op can fire every new base and transformation without exceeding four normal slots',()=>{for(const id of Object.keys(ARSENAL_ITEMS)){const w=new CoopWorld('courtyard',[{character:'knight',bonuses:{}},{character:'witch',bonuses:{}}]);const p=w.players[0];p.inv={[id]:ARSENAL_ITEMS[id].max};w.refresh(p);w.enemies=[];w.spawn('elite',0,{x:p.x+90,y:p.y});w.rehash();w.weapons(p,.03);assert(w.effects.length>0,id+' has a visible attack');assert(w.enemies[0].hp<w.enemies[0].maxHp,id+' deals damage');}const inv={halberd:1,bell:1,tome:1,sword:1};assert(coopEligible(inv).filter(id=>ARSENAL_ITEMS[id]?.kind==='weapon').every(id=>inv[id]));});
