import test from 'node:test';
import assert from 'node:assert/strict';
import {saveLayoutSnapshot} from '../public/layout-save.mjs';
import {retainLayout,listRecovery,readRecovery,clearRecovery} from '../public/layout-recovery.mjs';
import {templates} from '../public/layouts.mjs';
import {MAPS} from '../public/maps.mjs';
function storage(){const m=new Map();return {get length(){return m.size;},key:i=>[...m.keys()][i],setItem:(k,v)=>m.set(k,v),getItem:k=>m.get(k)||null,removeItem:k=>m.delete(k)};}
const p=templates(MAPS.firstfloor).find(p=>!p.locked),patch={id:p.id,source:p.id,x:p.x,y:p.y,angle:0};
function editor(){return {map:MAPS.firstfloor,history:{value:[patch]},revision:0,recoverySession:'tab-a',saved:'[]',status(t){this.message=t;},dirty(){return JSON.stringify(this.history.value)!==this.saved;},scheduleSave(){this.scheduled=true;}};}
test('save response preserves newer edits, saves their new base revision and schedules another save',async()=>{const old=globalThis.localStorage;globalThis.localStorage=storage();try{const e=editor();let finish;const task=saveLayoutSnapshot(e,()=>new Promise(r=>finish=r));const latest=[{...patch,angle:90}];e.history.value=latest;finish({revision:1,patches:[patch]});await task;assert.deepEqual(e.history.value,latest);assert(e.dirty()&&e.scheduled);assert.equal(e.revision,1);assert.equal(readRecovery('firstfloor','tab-a').revision,1);}finally{globalThis.localStorage=old;}});
test('publish stops if newer edits arrive during saving',async()=>{const old=globalThis.localStorage;globalThis.localStorage=storage();try{const e=editor();let finish,calls=0;const task=saveLayoutSnapshot(e,()=>{calls++;return new Promise(r=>finish=r);},true);e.history.value=[{...patch,angle:180}];finish({revision:1,patches:[patch]});await task;assert.equal(calls,1);assert.match(e.message,/before publishing again/);assert.equal(e.history.value[0].angle,180);}finally{globalThis.localStorage=old;}});
test('new tab editing and successful save leave old and legacy recovery copies intact',()=>{const old=globalThis.localStorage;globalThis.localStorage=storage();try{retainLayout('firstfloor',0,[patch]);retainLayout('firstfloor',1,[{...patch,angle:90}],'tab-a');retainLayout('firstfloor',2,[{...patch,angle:180}],'tab-b');assert.equal(listRecovery('firstfloor').length,3);clearRecovery('firstfloor',[{...patch,angle:180}],'tab-b');assert.equal(listRecovery('firstfloor').length,2);assert.equal(readRecovery('firstfloor','legacy').patches[0].angle,0);}finally{globalThis.localStorage=old;}});
test('restored sign-in exits guest mode while existing guest run checkpoints stay local',async()=>{const oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;globalThis.localStorage=storage();let online=false,checkpoints=0;globalThis.fetch=async(url)=>{if(url.includes('checkpoint'))checkpoints++;return online?Response.json({coins:123,achievements:{}}):Response.json({error:'unauthorized'},{status:401});};try{const m=await import('../public/progression.mjs?session-recovery-test');await m.loadAccount();assert(m.guestMode);const run=await m.api('run/start',{runId:crypto.randomUUID(),character:'knight',mapId:'courtyard'});const save=new m.RunSave(run.runId,()=>{});online=true;await m.loadAccount();assert.equal(m.guestMode,false);await save.save({gold:0,elapsed:0,kills:0},true);assert.equal(checkpoints,0);assert.equal(m.account.coins,123);online=false;await assert.rejects(()=>m.loadAccount(),e=>e.status===401);assert.equal(m.guestMode,false);}finally{globalThis.fetch=oldFetch;globalThis.localStorage=oldStorage;}});
