import test from 'node:test';import assert from 'node:assert/strict';
import {CHARACTERS} from '../public/characters.mjs';
import {calculateStats,passivePower,spendCharge,weaponMastery} from '../public/stats.mjs';
import {ITEMS,choices,chestRewards,eligibleItems,discardItem,canDiscard,eligibleRecipes} from '../public/rules.mjs';
test('all passives cap at eight and final rank counts as three upgrades',()=>{for(const item of Object.values(ITEMS).filter(i=>i.kind==='passive'))assert.equal(item.max,8);assert.equal(passivePower(7),7);assert.equal(passivePower(8),10);assert.equal(weaponMastery(8),1.25);});
test('live stats use character bases, permanent upgrades and passive mastery',()=>{const c=CHARACTERS.knight;const normal=calculateStats(c);assert.equal(normal.pickup,100);const t=calculateStats(c,{magnet:8,vitality:8,haste:8,might:8},{pickup:10,health:10});assert.ok(Math.abs(t.pickup-440)<1e-8);assert.equal(t.health,332);assert.equal(t.speed,224);assert.equal(t.damage,2.2);assert.equal(t.armor,2);assert.equal(calculateStats(CHARACTERS.witch).luck,20);});
test('banished items cannot appear in level rolls or chests',()=>{const banned=['sword','magnet'];for(let i=0;i<100;i++){assert.ok(choices({sword:2},Math.random,banned).every(id=>!banned.includes(id)));assert.ok(chestRewards({sword:2},Math.random,banned).rewards.every(r=>!banned.includes(r.id)));}assert.equal(eligibleRecipes({sword:8,frost:1},['winter']).length,0);});
test('discard frees a slot, removes levels and prevents rerolling; last weapon is protected',()=>{const inv={sword:5,wand:3,frost:1},banned=[];assert.equal(discardItem(inv,banned,'sword'),true);assert.ok(!eligibleItems(inv,banned).includes('sword'));assert.equal(canDiscard(inv,'wand'),false);assert.equal(discardItem(inv,banned,'wand'),false);assert.equal(discardItem(inv,banned,'frost'),true);assert.deepEqual(inv,{wand:3});});
test('reroll prefers new eligible options and finite charges cannot go below zero',()=>{const old=choices({sword:1},()=>.1);const next=choices({sword:1},()=>.1,[],3,old);assert.ok(next.every(id=>!old.includes(id)));const charges={...CHARACTERS.knight.charges};for(let i=0;i<4;i++)spendCharge(charges,'reroll');assert.equal(charges.reroll,0);assert.equal(CHARACTERS.knight.charges.reroll,3);});
