import test from 'node:test';
import assert from 'node:assert/strict';
import {CoopWorld} from '../public/coop-model.mjs';
import {CoopConnection,validSnapshot} from '../public/coop-network.mjs';
import {partyItems} from '../public/coop-party.mjs';
import {xpNeeded} from '../public/rules.mjs';
import {SEALS} from '../public/seals.mjs';
const config=[{character:'knight',bonuses:{},keepKey:true},{character:'witch',bonuses:{},keepKey:true}];
function world(map='courtyard'){const w=new CoopWorld(map,config,()=>.4);w.enemies=[];w.loot=[];w.spawnClock=999;w.weapons=()=>{};return w;}
const snapshot=w=>JSON.parse(JSON.stringify(w.snapshot()));
const act=(w,p,type,extra={})=>w.applyAction(p,{seq:p.actionSeq+1,type,offer:p.pending?.id,chest:p.chestResult?.id,...extra});
function choose(w,p,item=p.pending.options[0]){act(w,p,'choose',{item});}
test('collision with a chest while both gain levels preserves both offers and resumes after all acknowledgements',()=>{const w=world(),[a,b]=w.players;w.loot=[{id:1,kind:'xp',x:a.x,y:a.y,amount:xpNeeded(1)+xpNeeded(2)},{id:2,kind:'chest',x:a.x,y:a.y}];w.step(.03);assert.equal(a.pending.type,'chest');assert.equal(b.pending.type,'level');const chest=a.pending.id;choose(w,a);assert.equal(a.chestResult.id,chest);choose(w,b);const before=w.time;w.step(.03);assert.equal(w.time,before);assert(!a.pending);act(w,a,'chest_done');w.step(.03);assert.equal(a.pending.type,'level');choose(w,a);w.step(.03);assert(w.time>before);assert(validSnapshot(snapshot(w)));});
test('two chests at the same position are collected sequentially and a delayed old close cannot dismiss the next',()=>{const w=world(),p=w.players[0];w.loot=[1,2].map(id=>({id,kind:'chest',x:p.x,y:p.y}));w.step(.03);assert.equal(w.loot.length,1);choose(w,p);const old=p.chestResult.id;act(w,p,'chest_done');w.step(.03);assert.equal(w.loot.length,0);choose(w,p);const next=p.chestResult.id;assert.notEqual(next,old);act(w,p,'chest_done',{chest:old});assert.equal(p.chestResult.id,next);act(w,p,'chest_done');assert.equal(p.chestResult,null);assert.equal(p.chests,2);});
test('duplicate collection and delayed choice packets cannot grant rewards twice or overwrite a level offer',()=>{const w=world(),p=w.players[0],chest={id:1,kind:'chest',x:p.x,y:p.y};w.collect(p,chest);const pending=p.pending.id;w.collect(p,chest);assert.equal(p.chests,1);const cmd={seq:1,type:'choose',offer:pending,item:'random'};w.applyAction(p,cmd);const inventory={...p.inv},gold=w.gold;w.applyAction(p,{...cmd,seq:2});assert.deepEqual(p.inv,inventory);assert.equal(w.gold,gold);assert.equal(w.collect(p,{kind:'chest'}),false);act(w,p,'chest_done');w.offer(p);const id=p.pending.id;assert.equal(w.collect(p,{kind:'chest'}),false);assert.equal(p.pending.id,id);});
test('chests produce each reward count, upgrade only owned gear, and share passive effects and currency',()=>{for(const [roll,count] of [[.1,1],[.5,2],[.8,3],[.9,4],[.99,5]]){const w=world(),[a,b]=w.players;a.inv={sword:1,echo:1};w.refresh();let first=true;w.rng=()=>{if(first){first=false;return roll;}return .8;};w.collect(a,{kind:'chest'});choose(w,a);assert.equal(a.chestResult.rewards.length,count);assert(Object.keys(a.inv).every(id=>['sword','echo'].includes(id)));assert.equal(b.stats.amount,a.stats.amount);assert(!b.inv.echo);const guest=new CoopConnection({role:'guest'});guest.receiveState(snapshot(w));assert.deepEqual(guest.state.players[0].chestResult,a.chestResult);}});
test('currency-only chest at full mastery keeps inventory intact',()=>{const w=world(),p=w.players[0];p.inv={sword:8};w.rng=()=>.99;w.collect(p,{kind:'chest'});choose(w,p);assert.equal(p.chestResult.rewards.length,5);assert(p.chestResult.rewards.every(r=>r.type==='gold'));assert.equal(w.gold,p.chestResult.rewards.reduce((n,r)=>n+r.amount,0));assert.deepEqual(p.inv,{sword:8});});
test('borrowed fusion weapon remains eligible for upgrades and chest rewards after teammate transforms',()=>{const w=world(),[a,b]=w.players;a.inv={sword:8};b.inv={shield:8,echo:1};w.collect(a,{kind:'chest'});choose(w,a,'legion');assert.equal(b.inv.shield,8);b.inv.shield=7;assert(partyItems(w.players,b).includes('shield'));assert(!partyItems(w.players,a).includes('shield'));w.collect(b,{kind:'chest'});w.rng=()=>.6;choose(w,b);assert.equal(b.inv.shield,8);});
test('hearts heal an injured teammate without being wasted by a closer full-health player',()=>{const w=world(),[a,b]=w.players;b.hp-=20;b.x=a.x+5;b.y=a.y;w.loot=[{id:1,kind:'heart',amount:20,x:a.x,y:a.y}];w.step(.01);assert.equal(b.hp,b.stats.health);assert.equal(w.loot.length,0);w.loot=[{id:2,kind:'heart',amount:20,x:a.x,y:a.y}];w.step(.01);assert.equal(w.loot.length,1);});
test('one enemy projectile cannot damage both overlapping heroes',()=>{const w=world(),[a,b]=w.players;a.guard=10;b.x=a.x;b.y=a.y;const hp=[a.hp,b.hp];w.bolts=[{id:1,x:a.x,y:a.y,vx:0,vy:0,r:8,t:1,kind:'enemy',damage:10}];w.step(.01);assert.equal(w.players.filter((p,i)=>p.hp<hp[i]).length,1);});
test('a downed player or reward pause cannot summon guardians',()=>{const w=world('basement'),p=w.players[0];p.x=SEALS[0].x;p.y=SEALS[0].y;p.hp=0;act(w,p,'seal',{bit:1});assert.equal(w.activeSeal,0);p.hp=100;w.offer(w.players[1]);act(w,p,'seal',{bit:1});assert.equal(w.activeSeal,0);});
test('a stale open direct channel falls back, but continues probing for recovery',async()=>{const c=new CoopConnection({role:'guest'}),sent=[];c.channel={readyState:'open',bufferedAmount:0,send:v=>sent.push(v)};c.lastDirect=Date.now()-2000;assert(!c.direct());await c.sendDirect();assert.equal(sent.length,1);c.lastDirect=Date.now();assert(c.direct());});
// Minimal document adapter checks actual menu handlers and DOM replacement
// boundaries; it intentionally does not claim layout/GPU or live browser QA.
globalThis.Phaser={Scene:class{}};
const {CoopArena}=await import('../public/coop-ui.mjs');
function documentFixture(){const elements=new Map();const node=()=>({textContent:'',hidden:false,disabled:false,style:{},onclick:null,focus(){}});const overlay=node();Object.defineProperty(overlay,'innerHTML',{get(){return this.html||'';},set(html){this.html=html;elements.clear();elements.set('#overlay',overlay);for(const m of html.matchAll(/id="([^"]+)"/g))elements.set('#'+m[1],node());if(html.includes('class="chest-spin"'))elements.set('.chest-spin',node());}});elements.set('#overlay',overlay);return {querySelector:s=>elements.get(s)||null,elements,overlay};}
test('both actual menu paths reveal chests without spoilers, do not restart on peer choices, and send a scoped close',()=>{const original=globalThis.document;try{for(const own of [0,1]){const doc=documentFixture();globalThis.document=doc;const w=world(),p=w.players[own];w.rng=()=>.99;w.collect(p,{kind:'chest'});choose(w,p);const scene=new CoopArena({state:snapshot(w),own,conn:{lastPeer:Date.now()},art:id=>id,actions:[],actionSeq:0});scene.release=()=>{};scene.renderModal();assert.equal(doc.elements.get('#chest-rewards').innerHTML,'');assert.equal(scene.chestReveal.count,0);const button=doc.elements.get('#chest-next'),start=scene.chestReveal.started;button.onclick();assert.equal(scene.chestReveal.count,5);assert.equal(button.textContent,'Continue');w.offer(w.players[1-own]);choose(w,w.players[1-own]);scene.state=snapshot(w);scene.renderModal();assert.equal(doc.elements.get('#chest-next'),button);assert.equal(scene.chestReveal.started,start);button.onclick();assert.equal(scene.actions.at(-1).type,'chest_done');assert.equal(scene.actions.at(-1).chest,p.chestResult.id);assert(button.disabled);}}finally{globalThis.document=original;}});

test('co-op discard requires confirmation and cancel sends no action',()=>{const original=globalThis.document;try{const doc=documentFixture();globalThis.document=doc;const w=world(),p=w.players[0];p.inv={sword:1,wand:8};const scene=new CoopArena({state:snapshot(w),own:0,conn:{lastPeer:Date.now()},art:id=>id,actions:[],actionSeq:0});scene.release=()=>{};scene.renderModal=()=>{};scene.confirmDiscard('wand');assert.equal(scene.actions.length,0);assert.match(doc.overlay.innerHTML,/Costs one banish/);doc.elements.get('#coop-keep').onclick();assert.equal(scene.actions.length,0);scene.confirmDiscard('wand');doc.elements.get('#coop-discard').onclick();assert.equal(scene.actions.length,1);assert.equal(scene.actions[0].type,'discard');assert.equal(scene.actions[0].item,'wand');assert.equal(p.inv.wand,8);}finally{globalThis.document=original;}});
