import test from 'node:test';
import assert from 'node:assert/strict';
import {CoopWorld} from '../public/coop-model.mjs';
import {validSnapshot,CoopConnection} from '../public/coop-network.mjs';
import {EffectTimeline,enemyPresentation} from '../public/coop-presentation.mjs';
import {projectileArt} from '../public/combat-visuals.mjs';
import {MAPS} from '../public/maps.mjs';
const configs=[{character:'knight',bonuses:{},keepKey:true},{character:'witch',bonuses:{},keepKey:true}];
function world(){const w=new CoopWorld('courtyard',configs,()=>.4);w.enemies=[];w.loot=[];w.spawnClock=999;return w;}
const action=(w,p,type,extra={})=>w.applyAction(p,{seq:p.actionSeq+1,type,offer:p.pending?.id,chest:p.chestResult?.id,...extra});
const serial=w=>JSON.parse(JSON.stringify(w.snapshot()));
test('lethal damage, block, player injury, healing and exact gold generate shared feedback',()=>{const w=world(),p=w.players[0],q=w.players[1],e=w.spawn('normal',0,{x:p.x+100,y:p.y});w.damage(e,50,p);assert(e.dead);assert.equal(w.feedback.at(-1).text,'50');w.hurt(p,10);assert.equal(w.feedback.at(-1).text,'BLOCK');w.hurt(q,10);assert.equal(w.feedback.at(-1).text,'−10');assert(q.flash>0);w.collect(q,{kind:'heart',amount:5});assert.equal(w.feedback.at(-1).text,'+5');q.stats.greed=1.5;w.collect(q,{kind:'gold',amount:50});assert.equal(w.gold,75);assert.equal(w.feedback.at(-1).text,'+75 coins');const guest=new CoopConnection({role:'guest'});guest.receiveState(serial(w));assert.deepEqual(guest.state.feedback,w.feedback);assert(!validSnapshot({...serial(w),feedback:[{id:1,x:0,y:0,t:1,text:'x',color:'bad'}]}));});
test('short effects survive relay delays and repeated packets never replay the same effect',()=>{const w=world();w.weapons=()=>{};w.effect({kind:'slash',x:1,y:2,a:0,r:100,t:.22});for(let i=0;i<10;i++)w.step(.05);const f=w.effects[0];assert(f.t<0);const timeline=new EffectTimeline();assert.equal(timeline.update(serial(w).effects,.016).length,1);assert.equal(timeline.update(serial(w).effects,.2).length,0);assert.equal(timeline.update(serial(w).effects,.016).length,0);assert.equal(timeline.active.size,0);});
test('chest reward reveal pauses both players and requires collector acknowledgement',()=>{const w=world(),p=w.players[0];w.collect(p,{kind:'chest'});action(w,p,'choose',{item:'random'});assert(p.chestResult);const gold=w.gold;const time=w.time;w.step(.03);assert.equal(w.time,time);assert(validSnapshot(serial(w)));action(w,w.players[1],'chest_done');w.step(.03);assert.equal(w.time,time);action(w,p,'chest_done');w.step(.03);assert(w.time>time);assert.equal(w.gold,gold);});
test('slows expire and ice/hunt projectiles apply timed effects',()=>{const w=world(),p=w.players[0];w.weapons=()=>{};p.inv.frost=1;w.refresh();const e=w.spawn('elite',0,{x:p.x+400,y:p.y});w.damage(e,1,p);assert(e.slow>0);for(let i=0;i<35;i++)w.step(.05);assert.equal(e.slow,0);p.inv={};w.refresh();w.bolts=[{id:999,x:e.x,y:e.y,vx:0,vy:0,t:1,kind:'hunt',owner:0,damage:1,pierce:99,r:30,hit:new Set()}];w.step(.01);assert(e.slow>=.25);assert(e.slowTime>0);});
test('expired projectiles cannot hit and pending flask pools cannot damage early',()=>{const w=world(),p=w.players[0];p.inv={};const e=w.spawn('elite',0,{x:p.x+350,y:p.y});const hp=e.hp;w.bolts=[{id:998,x:e.x,y:e.y,vx:0,vy:0,t:0,kind:'arcane',owner:0,damage:100,pierce:1,r:40,hit:new Set()}];w.pools=[{id:999,x:e.x,y:e.y,t:3,delay:.4,r:100,owner:0,damage:100,tick:0,kind:'hex'}];w.step(.03);assert.equal(e.hp,hp);w.pools[0].delay=0;w.step(.03);assert(e.hp<hp);});
test('eligible teammate can collect an owned boss relic even with partner standing on it',()=>{const w=world(),[a,b]=w.players;a.inv.echo=1;w.refresh();b.x=a.x+5;b.y=a.y;const l={id:99,kind:'passive',item:'echo',x:b.x,y:b.y,amount:1};w.loot=[l];w.step(.03);assert.equal(a.inv.echo,2);assert(!b.inv.echo);assert(!w.loot.length);});
test('enemy frames align wolves and witches, guardian art remains unique, veterans show damaged health',()=>{assert.equal(enemyPresentation({tier:'normal',type:1}).origin,.85);assert.equal(enemyPresentation({tier:'normal',type:2}).origin,.86);const seals=[1,2,4].map(seal=>enemyPresentation({tier:'boss',type:0,seal}));assert(seals.every(a=>a.texture==='guardians'));assert.equal(new Set(seals.map(a=>a.frame)).size,3);assert(enemyPresentation({tier:'veteran',type:0,hp:10,maxHp:20}).healthBar);assert.equal(enemyPresentation({tier:'elite',type:0,flash:.1}).tint,0xffffff);});
// Exercise the actual Phaser scene methods with a recording display API. This
// checks host and serialized guest render paths without pretending to be GPU QA.
globalThis.Phaser={Scene:class{}};
const {CoopArena}=await import('../public/coop-ui.mjs');
function display(x=0,y=0,texture='',frame=''){const v={x,y,texture:{key:texture},frame,anims:{isPlaying:false,isPaused:false,pause(){this.isPaused=true;},resume(){this.isPaused=false;}}};for(const name of ['setOrigin','setDisplaySize','setDepth','setFlipX','setAlpha','setTint','setRotation','setScale','setSize','fillStyle','fillRect','fillCircle','fillEllipse','lineStyle','strokeEllipse','strokeCircle','beginPath','moveTo','lineTo','closePath','fillPath','strokePath','lineBetween','arc','clear'])v[name]=(...args)=>{v[name+'Args']=args;return v;};v.setPosition=(x,y)=>{v.x=x;v.y=y;return v;};v.setTexture=(key,frame)=>{v.texture.key=key;v.frame=frame;return v;};v.setFrame=f=>{v.frame=f;return v;};v.clearTint=()=>v;v.stop=()=>v;v.play=key=>{v.anims.currentAnim={key};v.anims.isPlaying=true;return v;};v.destroy=()=>{v.destroyed=true;};return v;}
function scene(state,own){const s=new CoopArena({state});Object.assign(s,{own,visuals:new Map(),floaters:new Map(),effectTimeline:new EffectTimeline(),feedbackTimeline:new EffectTimeline(),fx:display(),groundFx:display(),bars:display(),floor:display(),map:MAPS[state.mapId],camera:{worldView:{x:0,y:0,width:1000,height:800,centerX:500,centerY:400},startFollow(){}},textures:{exists:()=>true},add:{sprite:display,text:(x,y,text)=>Object.assign(display(x,y),{text})},blocked:()=>false,renderChestMarkers:()=>{}});return s;}
test('actual host and guest scene draw proper projectiles, floating damage, enemy flashes and clean up objects',()=>{const w=world(),p=w.players[0];for(const kind of ['arrow','trueflight','soul','hunt','knight'])w.projectile(p,0,100,1,kind);const e=w.spawn('veteran',1,{x:p.x+100,y:p.y});w.damage(e,1,p);for(const own of [0,1]){const s=scene(serial(w),own);s.renderWorld(.016);for(const b of w.bolts){const v=s.visuals.get('b'+b.id),art=projectileArt(b.kind);assert.equal(v.texture.key,art.texture);assert.equal(v.frame,art.frame);assert.equal(v.setDisplaySizeArgs[0],art.size);}assert.equal(s.visuals.get('e'+e.id).setTintArgs[0],0xffffff);assert.equal([...s.floaters.values()][0].text,'1');s.state.bolts=[];s.state.enemies=[];s.state.feedback=[];for(let i=0;i<70;i++)s.renderWorld(.016);assert.equal(s.floaters.size,0);assert.equal(s.visuals.size,2);}});
test('dense snapshots stay valid and below relay payload limits',()=>{const w=world();const p=w.players[0];for(let i=0;i<360;i++)w.spawn('elite',0,{x:p.x+i,y:p.y+400});for(let i=0;i<240;i++)w.projectile(p,0,100,1,'arrow');for(let i=0;i<330;i++)w.drop('xp',p.x+i,p.y,1);for(let i=0;i<80;i++)w.feedbackText(p.x,p.y,'9999');for(let i=0;i<40;i++)w.effect({x:p.x,y:p.y,kind:'lightning',toX:p.x+50,toY:p.y+50,r:0,t:.24});const state=serial(w);assert(validSnapshot(state));assert(JSON.stringify(state).length<160000);});

test('breakable respawns cannot overflow the enemy cap and freeze guest updates',()=>{const w=world(),p=w.players[0];for(let i=0;i<360;i++)w.spawn('normal',0,{x:p.x+500,y:p.y});w.spawnBreakable();assert.equal(w.enemies.length,360);assert(validSnapshot(serial(w)));});
test('boss relic becomes gold when neither player can use it',()=>{const w=world(),p=w.players[0];w.players.forEach(q=>q.banned.push('echo'));w.loot=[{id:99,kind:'passive',item:'echo',x:p.x,y:p.y,amount:1}];w.step(.03);assert.equal(w.gold,50);assert.equal(w.loot.length,0);});

test('royal encounters render distinct frames and charge warnings for host and guest',async()=>{const {CLAIMS,CHAMPION}=await import('../public/royal-objectives.mjs');const w=new CoopWorld('firstfloor',[{character:'knight',bonuses:{}},{character:'witch',bonuses:{}}],()=>.5);for(const q of [CLAIMS[0],CLAIMS[1],CHAMPION])w.spawnRoyal(q);const royal=w.enemies.filter(e=>e.royal);royal[0].charge={x:2040,y:3360,t:.5};for(const own of [0,1]){const s=scene(serial(w),own);s.renderWorld(.016);for(const e of royal){const v=s.visuals.get('e'+e.id);assert.equal(v.texture.key,'royal-enemies');assert.equal(v.frame,'cell'+e.royalArt);}assert.deepEqual(s.groundFx.strokeCircleArgs,[2040,3360,90]);}});

test('Crownless character and Crownshards effects use approved textures on host and guest',()=>{const w=new CoopWorld('courtyard',[{character:'crownless',bonuses:{}},{character:'knight',bonuses:{}}],()=>.5),p=w.players[0];w.enemies=[];w.spawn('veteran',0,{x:p.x+100,y:p.y});w.rehash();w.weapons(p,.03);assert(w.effects.some(f=>f.kind==='crownblade'));for(const own of [0,1]){const s=scene(serial(w),own);s.renderWorld(.016);assert.equal(s.visuals.get('p0').texture.key,'crownless');const blade=w.effects.find(f=>f.kind==='crownblade');assert.equal(s.visuals.get('arsenal:'+blade.id).texture.key,'crown-items');}});
