import test from 'node:test';
import assert from 'node:assert/strict';
import {CoopWorld} from '../public/coop-model.mjs';
import {partyItems,partyRecipes} from '../public/coop-party.mjs';
const configs=[{character:'knight',bonuses:{},keepKey:true},{character:'witch',bonuses:{},keepKey:true}];
const world=(map='courtyard')=>new CoopWorld(map,configs,()=>.2);
const act=(w,p,type,extra={})=>w.applyAction(p,{seq:p.actionSeq+1,type,offer:p.pending?.id,travel:w.transition?.id,...extra});
test('same starting weapon cannot begin a party',()=>{assert.throws(()=>new CoopWorld('courtyard',[configs[0],configs[0]]),/different starting/);});
test('owned party equipment is excluded from offers and pending cards reserve unowned items',()=>{const w=world(),[a,b]=w.players;b.inv.echo=1;assert(!partyItems(w.players,a).includes('echo'));assert(!partyItems(w.players,a).includes('lantern'));w.offer(a);w.offer(b);assert(a.pending.options.every(id=>!b.pending.options.includes(id)));});
test('stale simultaneous choice cannot claim an item after partner takes it',()=>{const w=world(),[a,b]=w.players;w.offer(a,'level',['echo']);w.offer(b,'level',['echo']);const old=b.pending.id;act(w,a,'choose',{item:'echo'});w.applyAction(b,{seq:b.actionSeq+1,type:'choose',offer:old,item:'echo'});assert(a.inv.echo);assert(!b.inv.echo);assert(!b.pending.options.includes('echo'));});
test('boss passive exceeds capacity but cannot duplicate a teammate passive',()=>{const w=world(),[a,b]=w.players;a.inv={sword:1,might:8,haste:8,vitality:8,magnet:8};b.inv={lantern:1,echo:8,frost:8};w.collect(a,{kind:'passive'});assert(a.inv.hourglass);assert(!a.inv.echo);assert(!a.inv.frost);});
test('borrowed passive satisfies transformation, remains with partner and has to meet rank',()=>{const w=world(),[a,b]=w.players;a.inv={bell:8};b.inv={lantern:1,echo:1};assert(partyRecipes(w.players,a).some(r=>r.id==='tempest'));w.collect(a,{kind:'chest'});act(w,a,'choose',{item:'tempest'});assert(a.inv.tempest);assert(!a.inv.bell);assert.equal(b.inv.echo,1);assert(!partyItems(w.players,b).includes('bell'));});
test('weapon fusion requires both max weapons on the evolving player and frees a slot',()=>{const w=world(),[a,b]=w.players;a.inv={sword:8,frost:1};b.inv={shield:8};assert(!partyRecipes(w.players,a).some(r=>r.id==='legion'));b.inv={lantern:1};a.inv.shield=7;assert(!partyRecipes(w.players,a).some(r=>r.id==='legion'));a.inv.shield=8;assert(partyRecipes(w.players,a).some(r=>r.id==='legion'));w.collect(a,{kind:'chest'});act(w,a,'choose',{item:'legion'});assert(a.inv.legion);assert(!a.inv.sword&&!a.inv.shield);assert.equal(a.inv.frost,1);assert.equal(Object.keys(a.inv).filter(id=>['legion','sword','shield'].includes(id)).length,1);});
test('removing a borrowed ingredient invalidates an already offered chest transformation',()=>{const w=world(),[a,b]=w.players;a.inv={sword:8};b.inv={lantern:1,frost:1};w.collect(a,{kind:'chest'});const old=a.pending.id;w.pauses[1]=true;act(w,b,'discard',{item:'frost'});w.applyAction(a,{seq:a.actionSeq+1,type:'choose',offer:old,item:'winter'});assert(!a.inv.winter);assert(a.inv.sword);assert.deepEqual(a.pending.options,['random']);});
function gather(w){const at=w.map.gate||w.map.stairs;w.players.forEach((p,i)=>Object.assign(p,{x:at.x+i*40,y:at.y}));}
function readyTravel(w){const [a,b]=w.players;gather(w);act(w,a,'travel');assert(w.transition);act(w,a,'travel_confirm');act(w,b,'travel_confirm');if(w.transition.phase==='comic'){act(w,a,'travel_skip');act(w,b,'travel_skip');}assert.equal(w.transition.phase,'prepare');}
function prepare(w,index){act(w,w.players[index],'travel_prepared',{config:{bonuses:{},keepKey:true,chartedMaps:['courtyard','basement']}});}
test('gate requires both previously earned keys even after 30 minutes, and both players nearby',()=>{const w=world(),[a,b]=w.players;w.players.forEach(p=>p.keepKey=false);gather(w);w.time=1800;act(w,a,'travel');assert.equal(w.transition,null);a.keepKey=true;act(w,a,'travel');assert.equal(w.transition,null);b.keepKey=true;b.x+=1000;act(w,a,'travel');assert.equal(w.transition,null);gather(w);act(w,a,'travel');assert(w.transition);});
test('courtyard and basement transition only after both save acknowledgements; fresh build and monotonic network tick',()=>{const w=world();w.gold=75;w.players[0].inv.might=8;w.tick=100;readyTravel(w);prepare(w,0);w.step(.03);assert.equal(w.map.id,'courtyard');assert.equal(w.gold,75);prepare(w,1);w.step(.03);assert.equal(w.map.id,'basement');assert.equal(w.stage,1);assert(w.tick>100);assert.equal(w.gold,0);assert.deepEqual(w.players[0].inv,{sword:1});assert.equal(w.players[0].level,1);assert(w.players[0].charted);
 w.seals=7;readyTravel(w);prepare(w,0);prepare(w,1);w.step(.03);assert.equal(w.map.id,'firstfloor');assert.equal(w.stage,2);assert.equal(w.seals,0);});
test('dungeon staircase needs all seals this run even when first floor was previously unlocked',()=>{const w=world('basement');gather(w);act(w,w.players[0],'travel');assert.equal(w.transition,null);w.seals=7;act(w,w.players[0],'travel');assert(w.transition);});
test('cancel before saving keeps both players in current section; stale travel ack cannot skip stages',()=>{const w=world();gather(w);act(w,w.players[0],'travel');const id=w.transition.id;act(w,w.players[1],'travel_cancel');assert.equal(w.transition,null);act(w,w.players[0],'travel_prepared',{travel:id,config:{bonuses:{}}});assert.equal(w.map.id,'courtyard');assert.equal(w.transition,null);});

test('boss relic identity is fixed at drop and only its eligible owner can collect it',()=>{const w=world();w.drop('passive',100,100,1);const l=w.loot.at(-1),id=l.item;assert(id);w.rng=()=>.99;w.players[1].inv[id]=1;w.collect(w.players[0],l);assert(!l.dead);assert(!w.players[0].inv[id]);w.collect(w.players[1],l);assert(l.dead);assert.equal(w.players[1].inv[id],2);});

test('passive acquisition and upgrades benefit both players without transferring ownership',()=>{const w=world(),[a,b]=w.players;w.collect(a,{kind:'passive',item:'echo'});assert.equal(a.stats.amount,1);assert.equal(b.stats.amount,1);assert.equal(b.inv.echo,undefined);w.collect(a,{kind:'passive',item:'echo'});w.collect(a,{kind:'passive',item:'echo'});assert.equal(a.stats.amount,2);assert.equal(b.stats.amount,2);w.collect(b,{kind:'passive',item:'hourglass'});assert.equal(a.stats.cooldown,.92);assert.equal(b.stats.cooldown,.92);w.pauses[0]=true;act(w,a,'discard',{item:'echo'});assert.equal(a.stats.amount,0);assert.equal(b.stats.amount,0);assert.equal(b.inv.hourglass,1);});
test('shared health bonuses preserve damage and never revive a downed teammate',()=>{const w=world(),[a,b]=w.players;const initial=a.hp;a.hp-=10;b.hp=0;w.collect(a,{kind:'passive',item:'vitality'});assert.equal(a.hp,initial+10);assert.equal(b.hp,0);w.pauses[0]=true;act(w,a,'discard',{item:'vitality'});assert.equal(a.hp,initial);assert.equal(b.hp,0);});
test('host permanent charts reveal the selected section for both players only',()=>{for(const map of ['courtyard','basement','firstfloor']){const w=new CoopWorld(map,[{...configs[0],chartedMaps:[map]},configs[1]]);assert(w.players.every(p=>p.charted));const other=map==='courtyard'?'basement':'courtyard';const blank=new CoopWorld(other,[{...configs[0],chartedMaps:[map]},configs[1]]);assert(blank.players.every(p=>!p.charted));}});
test('travel applies host chart to both players in the new section',()=>{const w=world();readyTravel(w);act(w,w.players[0],'travel_prepared',{config:{bonuses:{},keepKey:true,chartedMaps:['basement']}});act(w,w.players[1],'travel_prepared',{config:{bonuses:{},keepKey:true,chartedMaps:[]}});w.step(.03);assert.equal(w.map.id,'basement');assert(w.players.every(p=>p.charted));});
