import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {CoopWorld} from '../public/coop-model.mjs';
import {slide} from '../public/dungeon.mjs';
const world=()=>new CoopWorld('courtyard',[{character:'knight',bonuses:{}},{character:'witch',bonuses:{}}],()=>.2);
const source=readFileSync(new URL('../public/game.js',import.meta.url),'utf8');
const soloMove=Function('slide','return ({'+source.match(/ moveEntity\(s,dx,dy,r\)\{[^\n]+/)[0]+'}).moveEntity')(slide);
test('co-op collides at the same furniture foot circle as solo on all four sides',()=>{for(const [dx,dy] of [[0,-30],[0,30],[-30,0],[30,0]]){const w=world(),ob={x:3000,y:2992,r:40};w.obstacles=[ob];const a={x:ob.x+dx,y:ob.y+dy},b={...a};soloMove.call({map:w.map,obstacles:[ob]},a,0,0,20);w.move(b,0,0,20);assert.deepEqual(b,a);assert.equal(Math.round(Math.hypot(b.x-ob.x,b.y-ob.y)),60);}});
test('full non-XP loot preserves every chest plus the new boss chest and passive',()=>{const w=world();w.loot=Array.from({length:330},(_,i)=>({id:++w.id,kind:'chest',x:2000+i,y:2000,amount:1}));w.drop('chest',5000,5000,1);w.drop('passive',5045,5000,1);assert(w.loot.length<=330);assert.equal(w.loot.filter(l=>l.kind==='chest').reduce((n,l)=>n+(l.amount||1),0),331);assert(w.loot.some(l=>l.kind==='chest'&&l.x===5000));assert(w.loot.some(l=>l.kind==='passive'&&l.x===5045));});
test('stacked chests are collected one at a time and stale acknowledgments cannot consume another',()=>{const w=world(),p=w.players[0],l={id:++w.id,kind:'chest',x:p.x,y:p.y,amount:2};w.collect(p,l);assert.equal(l.amount,1);assert(!l.dead);const offer=p.pending.id;w.applyAction(p,{seq:1,type:'choose',offer,item:'random'});const chest=p.chestResult.id;w.applyAction(p,{seq:2,type:'chest_done',chest});w.collect(p,l);assert(l.dead);assert.equal(p.chests,2);w.applyAction(p,{seq:3,type:'chest_done',chest});assert(p.pending);assert.notEqual(p.pending.id,offer);});
test('stacked boss passives retain remaining rewards and convert excess mastery to currency',()=>{const w=world(),p=w.players[0],l={kind:'passive',item:'echo',amount:3};p.inv.echo=7;w.collect(p,l);assert.equal(p.inv.echo,8);assert.equal(l.amount,2);assert(!l.dead);const before=w.gold;w.collect(p,l);assert(l.dead);assert.equal(w.gold-before,100);});

test('two brand-new heroes can fill all eight party weapon slots without duplicates',async()=>{const {STARTER_WEAPONS,lockedSignatureWeapons,unlockedCharacters}=await import('../public/weapon-unlocks.mjs');const {partyItems,partyRecipes}=await import('../public/coop-party.mjs');assert.equal(STARTER_WEAPONS.length,8);const w=world(),[a,b]=w.players;assert.deepEqual(unlockedCharacters({metrics:{}}),['knight','witch']);for(const [p,ids] of [[a,['shield','wand','flask']],[b,['bow','censer','halberd']]])for(const id of ids){assert(partyItems(w.players,p).includes(id));p.inv[id]=1;}assert.equal(new Set(w.players.flatMap(p=>Object.keys(p.inv))).size,8);assert(w.players.every(p=>Object.keys(p.inv).length===4));assert.deepEqual(new Set(lockedSignatureWeapons(['knight','witch'])),new Set(['bell','tome','crownshards']));a.inv.sword=a.inv.shield=8;assert(partyRecipes(w.players,a).some(r=>r.id==='legion'));delete a.inv.shield;b.inv.shield=8;assert(!partyRecipes(w.players,a).some(r=>r.id==='legion'));});
test('compaction conserves mixed loot and snapshots stay within relay limits',async()=>{const {compactLoot}=await import('../public/loot-capacity.mjs');const {validSnapshot}=await import('../public/coop-network.mjs');const w=world();w.loot=Array.from({length:330},(_,i)=>({id:++w.id,kind:i%3===0?'chest':i%3===1?'passive':'gold',item:i%3===1?'echo':null,amount:i%3===2?10:1,x:3000+i,y:3000}));const totals=()=>Object.fromEntries(['chest','passive','gold'].map(kind=>[kind,w.loot.filter(l=>l.kind===kind).reduce((n,l)=>n+l.amount,0)]));const before=totals();assert(compactLoot(w.loot));assert.deepEqual(totals(),before);for(let i=0;i<100;i++)w.drop('chest',5000,5000,1);assert.equal(totals().chest,before.chest+100);assert(w.loot.length<=330);assert(validSnapshot(JSON.parse(JSON.stringify(w.snapshot()))));assert(JSON.stringify(w.snapshot()).length<160000);});
