import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {MAPS,mapProps} from '../public/maps.mjs';
import {templates,validateLayout,resolveProps,LayoutHistory,mapAtVersion,installBundle,warnings} from '../public/layouts.mjs';
import {handleLayouts} from '../server/layouts.mjs';
import {CoopWorld} from '../public/coop-model.mjs';
import {validSnapshot} from '../public/coop-network.mjs';
function setup(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle',import.meta.url)).filter(p=>p.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));const statement=(query,args=[])=>({bind:(...a)=>statement(query,a),first:async()=>sql.prepare(query).get(...args)||null,run:async()=>sql.prepare(query).run(...args)});const call=async(path,body,email='jacobchapman3@gmail.com',extra={})=>{const r=await handleLayouts(new Request('https://game.test/api/layouts'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(email?{'oai-authenticated-user-email':email}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})}),{DB:{prepare:statement}});return {status:r.status,...await r.json()};};return {call};}
const base=templates(MAPS.firstfloor).find(p=>!p.locked&&p.atlas==='royal-props'&&p.frame===1),patch={id:base.id,source:base.id,x:base.x+24,y:base.y,angle:90};
test('stable decor identities, validation, locked quest objects, duplication and deletion',()=>{for(const map of Object.values(MAPS)){const list=templates(map);assert.equal(new Set(list.map(p=>p.id)).size,list.length);}assert.equal(validateLayout('firstfloor',[patch])[0].angle,90);const locked=templates(MAPS.firstfloor).find(p=>p.locked);assert.throws(()=>validateLayout('firstfloor',[{...patch,id:locked.id,source:locked.id}]));assert.throws(()=>validateLayout('firstfloor',[{...patch,x:-10}]));assert.throws(()=>validateLayout('firstfloor',[patch,patch]));const copy={...patch,id:'copy-'+crypto.randomUUID()};const props=resolveProps(MAPS.firstfloor,[patch,copy]);assert.equal(props.length,templates(MAPS.firstfloor).length+1);assert.equal(resolveProps(MAPS.firstfloor,[{...patch,deleted:true}]).length,templates(MAPS.firstfloor).length-1);assert(warnings(MAPS.firstfloor,{...base,x:4920,y:5800},[]).some(w=>w.includes('carpet')));});
test('undo and redo preserve independent snapshots and branch edits',()=>{const h=new LayoutHistory();h.set([patch]);h.set([]);h.undo();assert.deepEqual(h.value,[patch]);h.redo();assert.deepEqual(h.value,[]);h.undo();h.set([{...patch,x:patch.x+24}]);assert.equal(h.future.length,0);});
test('anonymous and non-owner cannot read drafts or mutate layouts; cross-site owner writes rejected',async()=>{const {call}=setup();assert.equal((await call('/access',undefined,null)).owner,false);assert.equal((await call('/draft?map=firstfloor',undefined,null)).status,401);assert.equal((await call('/draft?map=firstfloor',{revision:0,patches:[patch]},'friend@example.com')).status,403);assert.equal((await call('/draft?map=firstfloor',{revision:0,patches:[patch]},'jacobchapman3@gmail.com',{origin:'https://evil.test'})).status,403);assert.equal((await call('',undefined,null)).version,0);});
test('drafts survive reload, stale saves conflict, publishing preserves other sections and old revisions',async()=>{const {call}=setup();let d=await call('/draft?map=firstfloor',{revision:0,patches:[patch]});assert.equal(d.status,200);assert.equal((await call('/draft?map=firstfloor')).patches[0].x,patch.x);assert.equal((await call('')).version,0);assert.equal((await call('/draft?map=firstfloor',{revision:0,patches:[]})).status,409);let pub=await call('/publish?map=firstfloor',{revision:1});const first=pub.version;assert.equal((await call('?version='+first,undefined,null)).bundle.firstfloor[0].angle,90);assert.equal((await call('/publish?map=firstfloor',{revision:0})).status,409);await call('/draft?map=basement',{revision:0,patches:[]});await call('/publish?map=basement',{revision:1});assert.equal((await call('')).bundle.firstfloor[0].x,patch.x);await call('/draft?map=firstfloor',{revision:1,patches:[]});await call('/publish?map=firstfloor',{revision:2});assert.deepEqual((await call('')).bundle.firstfloor,[]);assert.equal((await call('?version='+first)).bundle.firstfloor.length,1);});
test('solo and co-op pin the same props and collision through later publications and travel',()=>{installBundle(991,{firstfloor:[patch]});const solo=mapAtVersion('firstfloor',991);const w=new CoopWorld('firstfloor',[{character:'knight',layoutVersion:991},{character:'witch'}],()=>.5);assert.equal(mapProps(solo).find(p=>p.id===patch.id).x,patch.x);assert.equal(w.obstacles.find(p=>p.id===patch.id).y,patch.y-8);assert(validSnapshot(w.snapshot()));installBundle(992,{firstfloor:[]});assert.equal(mapProps(solo).find(p=>p.id===patch.id).angle,90);assert.equal(w.snapshot().layoutVersion,991);w.transition={target:'throne',prepared:[true,true],configs:w.configs};assert(w.advanceStage());assert.equal(w.layoutVersion,991);assert.throws(()=>mapAtVersion('firstfloor',999999));});
