import test from 'node:test';
import assert from 'node:assert/strict';
import {MAPS,mapProps} from '../public/maps.mjs';
import {chartSpot} from '../public/minimap.mjs';
import {guestRequest} from '../public/guest.mjs';
test('both maps have clear starts, reachable gate and available map parchment',()=>{for(const map of Object.values(MAPS)){const obstacles=mapProps(map).filter(p=>p.r).map(p=>({x:p.x,y:p.y-8,r:p.r}));assert.ok(obstacles.every(o=>Math.hypot(o.x-map.spawn.x,o.y-map.spawn.y)>o.r+15));assert.ok(chartSpot(obstacles,()=>0,map.chartSpots));if(map.gate)assert.ok(obstacles.every(o=>Math.hypot(o.x-map.gate.x,o.y-map.gate.y-130)>o.r+15));}});
test('guest key and reward persist across reload and repeated saves',()=>{const old=globalThis.localStorage;let saved=JSON.stringify({profile:{coins:0,speed:0,health:0,damage:0,pickup:0},runs:{}});globalThis.localStorage={getItem:()=>saved,setItem:(k,v)=>saved=v};try{assert.throws(()=>guestRequest('run/start',{runId:'locked',mapId:'basement'}));guestRequest('run/start',{runId:'court'});const body={runId:'court',gold:20,elapsed:1800,kills:10,finished:true};guestRequest('run/checkpoint',body);guestRequest('run/checkpoint',body);assert.equal(guestRequest('profile').coins,520);guestRequest('purchase',{upgrade:'speed',rank:0});assert.equal(guestRequest('profile').coins,490);assert.equal(guestRequest('run/start',{runId:'down',mapId:'basement'}).mapId,'basement');assert.equal(JSON.parse(saved).profile.keepKey,true);}finally{globalThis.localStorage=old;}});

test('dungeon rooms, chart locations and every passage connect to the descent',async()=>{const {TILE,flowField,walkable}=await import('../public/dungeon.mjs');const m=MAPS.basement,field=flowField(m,m.spawn);m.dungeon.tiles.forEach((t,i)=>{if(t)assert.ok(field[i]>=0,'unreachable floor '+i);});for(const p of m.chartSpots)assert.ok(walkable(m,p.x,p.y,30));for(const [x,y,w,h] of m.dungeon.rooms)assert.ok(walkable(m,(x+w/2)*TILE,(y+h/2)*TILE,45));});
test('wall collision resists large knockbacks and enemy spawn corrections stay on floor',async()=>{const {slide,walkable,spawnPoint,clearLine}=await import('../public/dungeon.mjs');const m=MAPS.basement,s={...m.spawn};slide(m,s,0,20000,20);assert.ok(walkable(m,s.x,s.y,20));assert.ok(s.y<m.h-20);assert.equal(clearLine(m,m.spawn,{x:100,y:100}),false);for(const p of [{x:0,y:0},{x:4700,y:3700},{x:1400,y:2100}]){const q=spawnPoint(m,m.spawn,p);assert.ok(walkable(m,q.x,q.y,45));assert.ok(Math.hypot(q.x-m.spawn.x,q.y-m.spawn.y)>=190);}const court={...MAPS.courtyard.spawn};slide(MAPS.courtyard,court,0,-9000,13);assert.ok(court.y>=MAPS.courtyard.gate.y+13);});

test('expanded wings and first floor remain fully connected, seals and stairs are reachable',async()=>{const {flowField,walkable}=await import('../public/dungeon.mjs');const {SEALS}=await import('../public/seals.mjs');for(const m of [MAPS.basement,MAPS.firstfloor]){const field=flowField(m,m.spawn);m.dungeon.tiles.forEach((v,i)=>{if(v)assert.ok(field[i]>=0);});assert.ok(walkable(m,m.spawn.x,m.spawn.y,30));}for(const q of [...SEALS,MAPS.basement.stairs])assert.ok(walkable(MAPS.basement,q.x,q.y,30));});
test('guest seals persist across dungeon runs, unlock first floor and pay once',()=>{const old=globalThis.localStorage;let saved=JSON.stringify({profile:{coins:0,speed:0,health:0,damage:0,pickup:0,keepKey:true},runs:{}});globalThis.localStorage={getItem:()=>saved,setItem:(k,v)=>saved=v};try{for(const bit of [1,2,4]){guestRequest('run/start',{runId:'seal'+bit,mapId:'basement'});const body={runId:'seal'+bit,gold:0,elapsed:0,kills:1,seals:bit,finished:true};guestRequest('run/checkpoint',body);guestRequest('run/checkpoint',body);}let p=guestRequest('profile');assert.equal(p.sealMask,7);assert.equal(p.coins,750);assert.ok(p.achievements.completed.includes('out_of_depths'));assert.equal(guestRequest('run/start',{runId:'floor',mapId:'firstfloor'}).mapId,'firstfloor');guestRequest('purchase',{upgrade:'speed',rank:0});assert.equal(guestRequest('profile').coins,720);}finally{globalThis.localStorage=old;}});

test('guest chart unlock survives reload and stays specific to its section',()=>{const old=globalThis.localStorage;let saved=JSON.stringify({profile:{coins:0,speed:0,health:0,damage:0,pickup:0,keepKey:true},runs:{}});globalThis.localStorage={getItem:()=>saved,setItem:(k,v)=>saved=v};try{guestRequest('run/start',{runId:'chart',mapId:'basement'});const body={runId:'chart',gold:0,elapsed:0,kills:0,charted:true,finished:false};guestRequest('run/checkpoint',body);guestRequest('run/checkpoint',{...body,charted:false,finished:true});assert.deepEqual(guestRequest('profile').chartedMaps,['basement']);assert.deepEqual(guestRequest('run/start',{runId:'next',mapId:'basement'}).profile.chartedMaps,['basement']);assert.equal(JSON.parse(saved).runs.chart.charted,true);}finally{globalThis.localStorage=old;}});
