import test from 'node:test';
import assert from 'node:assert/strict';
import {catalogItems,recipeView,achievementView,mountGrimoire} from '../public/reference-ui.mjs';
import {ITEMS,RECIPES} from '../public/rules.mjs';
import {ACHIEVEMENTS,achievementState} from '../public/achievements.mjs';
test('catalog covers current equipment and finds transformations through ingredient names',()=>{for(const [tab,predicate] of [['weapons',i=>i.kind==='weapon'&&!i.evolved],['passives',i=>i.kind==='passive'],['transforms',i=>i.evolved]])assert.deepEqual(catalogItems(tab).map(([id])=>id),Object.keys(ITEMS).filter(id=>predicate(ITEMS[id])));assert(catalogItems('transforms','Hourglass').some(([id])=>id==='sabbath'));assert.equal(catalogItems('weapons','nonexistent123').length,0);});
test('recipe readiness shares passive ingredients but never a teammate fusion weapon',()=>{const legion=RECIPES.find(r=>r.id==='legion'),sabbath=RECIPES.find(r=>r.id==='sabbath'),players=[{id:0,inv:{sword:8,flask:8},banned:[]},{id:1,inv:{shield:8,hourglass:1},banned:[]}];const opts={players,own:0,inv:players[0].inv};assert(!recipeView(legion,opts).ready);const view=recipeView(sabbath,opts);assert(view.ready);assert.equal(view.ingredients.find(n=>n.id==='hourglass').owner,1);assert.equal(view.ingredients.find(n=>n.id==='hourglass').consumed,false);players[0].inv.shield=8;delete players[1].inv.shield;assert(recipeView(legion,opts).ready);});
test('mastery checklist does not invent historical evidence and preserves finish requirement',()=>{const a=ACHIEVEMENTS.find(a=>a.id==='unbroken_watch'),progress=achievementState({bestTime:1800});const empty=achievementView(a,progress);assert(empty.checks.every(c=>!c.met));const live=achievementView(a,progress,{mastery:1,elapsed:720,closed:false});assert.deepEqual(live.checks.map(c=>c.met),[true,true,false]);assert(live.underway&&!live.done);const completed=achievementView(a,achievementState({sentinelUnlocked:1}));assert(completed.done&&completed.checks.every(c=>c.met));});
test('catalog search updates results without rebuilding the active input',()=>{const nodes=new Map();const root={set innerHTML(html){this.html=html;nodes.clear();for(const id of ['reference-back','reference-search','reference-results'])nodes.set('#'+id,{value:'',innerHTML:''});},querySelector:s=>nodes.get(s),querySelectorAll:()=>[]};mountGrimoire({root,art:id=>id,progress:achievementState(),back:()=>{}});const input=nodes.get('#reference-search');input.oninput({target:{value:'Arcane Wand'}});assert.equal(root.querySelector('#reference-search'),input);assert(root.querySelector('#reference-results').innerHTML.includes('Arcane Wand'));assert(!root.querySelector('#reference-results').innerHTML.includes('<h3>Longsword</h3>'));assert(root.html.includes('Reference view'));});
