import test from 'node:test';import assert from 'node:assert/strict';
import {bonusPassive,breakableLoot,flaskPattern,censerStats} from '../public/rewards.mjs';
import {ITEMS,chestRewards,eligibleItems} from '../public/rules.mjs';
import {calculateStats,wandProjectileCount} from '../public/stats.mjs';import {CHARACTERS} from '../public/characters.mjs';
test('boss relic can select seventh passive while respecting banishes and maximum levels',()=>{const ids=Object.keys(ITEMS).filter(id=>ITEMS[id].kind==='passive'),inv=Object.fromEntries(ids.slice(0,6).map(id=>[id,8]));assert.equal(bonusPassive(inv,[],()=>0),ids[6]);assert.equal(bonusPassive(inv,[ids[6]],()=>0),null);assert.ok(!eligibleItems(inv).includes(ids[6]));});
test('Sabbath replaces max Hex Flask while keeping Hourglass',()=>{const r=chestRewards({flask:8,hourglass:1},()=>.1);assert.deepEqual(r.inventory,{sabbath:1,hourglass:1});assert.ok(!eligibleItems(r.inventory).includes('flask'));assert.equal(chestRewards({flask:8,hourglass:1},()=>.1,['sabbath']).rewards[0].type,'gold');});
test('Echo and Hourglass milestones give finite stronger final bonuses',()=>{const low=calculateStats(CHARACTERS.knight,{echo:1,hourglass:1}),max=calculateStats(CHARACTERS.knight,{echo:8,hourglass:8});assert.equal(low.amount,1);assert.equal(max.amount,6);assert.equal(low.cooldown,.92);assert.equal(max.cooldown,.2);assert.equal(max.projectileSpeed,1.4);});
test('flask throw patterns progress into overlapping rings and gain extra projectiles',()=>{assert.equal(flaskPattern(1).count,1);assert.equal(flaskPattern(6).ring,true);assert.equal(flaskPattern(8).count,6);const q=flaskPattern(8,6,true);assert.equal(q.count,14);assert.ok(q.duration>q.cooldown);assert.ok(2*q.poolRadius>2*q.radius*Math.sin(Math.PI/8));assert.ok(censerStats(8).damage>censerStats(7).damage*1.5);});
test('breakables can give healing, XP, or bounded coin rewards',()=>{assert.equal(breakableLoot(0,()=>.1).kind,'heart');assert.equal(breakableLoot(0,()=>.3).kind,'xp');const r=breakableLoot(0,()=>.9);assert.equal(r.kind,'gold');assert.ok(r.amount>=5&&r.amount<=12);});

test('Echo projectiles apply to a wand acquired later and disappear when Echo is discarded',()=>{const inv={sword:1,echo:5};let stats=calculateStats(CHARACTERS.knight,inv);inv.wand=1;stats=calculateStats(CHARACTERS.knight,inv);assert.equal(wandProjectileCount(inv.wand,stats),4);assert.equal(wandProjectileCount(8,stats),7);delete inv.echo;stats=calculateStats(CHARACTERS.knight,inv);assert.equal(wandProjectileCount(inv.wand,stats),1);});
test('player can choose either competing Longsword transformation without losing unrelated ingredients',()=>{const inv={sword:8,shield:8,frost:1};const winter=chestRewards(inv,()=>.1,[],'winter');assert.deepEqual(winter.inventory,{shield:8,frost:1,winter:1});const legion=chestRewards(inv,()=>.1,[],'legion');assert.deepEqual(legion.inventory,{frost:1,legion:1});assert.deepEqual(inv,{sword:8,shield:8,frost:1});assert.equal(winter.rewards.length,1);assert.equal(legion.rewards.length,1);assert.throws(()=>chestRewards(inv,()=>.1,['legion'],'legion'));});
