import test from 'node:test';
import assert from 'node:assert/strict';
import {createClaims,startClaim,tickClaims,claimDeath,claimsComplete,CLAIMS,BANNERS,FOUNTAIN,KING,royalCombat} from '../public/royal-objectives.mjs';
import {MAPS,mapProps} from '../public/maps.mjs';
import {walkable} from '../public/dungeon.mjs';
import {CoopWorld} from '../public/coop-model.mjs';
import {validSnapshot} from '../public/coop-network.mjs';
const configs=[{character:'knight',bonuses:{}},{character:'witch',bonuses:{}}];
test('claims reset each run; both captains, full ritual and champion are required',()=>{const s=createClaims(),spawned=[],spawn=q=>(spawned.push(q),true);for(const q of CLAIMS){assert.ok(startClaim(s,q.id,spawn));assert.equal(startClaim(s,q.id,spawn),false);}claimDeath(s,'west');claimDeath(s,'east');for(let i=0;i<3;i++)claimDeath(s,'banner'+i);tickClaims(s,[],1,spawn,()=>{});assert.equal(s.champion,1);assert.equal(spawned.filter(q=>q.id==='champion').length,1);tickClaims(s,[],1,spawn,()=>{});assert.equal(spawned.filter(q=>q.id==='champion').length,1);claimDeath(s,'champion');assert.equal(claimsComplete(s),false);const rewards=[];for(let i=0;i<1200;i++)tickClaims(s,[{...CLAIMS[2],hp:10}],.05,spawn,(kind)=>rewards.push(kind));assert.equal(claimsComplete(s),true);assert.equal(rewards.filter(k=>k==='chest').length,1);assert.equal(claimsComplete(createClaims()),false);});
test('ritual holds progress on retreat and downed heroes cannot advance it',()=>{const s=createClaims();s.tome=1;tickClaims(s,[{...CLAIMS[2],hp:1}],10,()=>true,()=>{});tickClaims(s,[{...CLAIMS[2],hp:0}],10,()=>true,()=>{});tickClaims(s,[{x:0,y:0,hp:10}],10,()=>true,()=>{});assert.equal(s.ritual,10);});
test('all royal objectives and throne spawn have collision-safe positions',()=>{for(const q of [...CLAIMS,...BANNERS,FOUNTAIN]){assert.ok(walkable(MAPS.firstfloor,q.x,q.y,40),q.id||'prop');for(const o of mapProps(MAPS.firstfloor).filter(o=>o.r))assert.ok(Math.hypot(q.x-o.x,q.y-(o.y-8))>o.r+20,q.id||'prop');}assert.ok(walkable(MAPS.throne,KING.x,KING.y,50));assert.ok(walkable(MAPS.throne,MAPS.throne.spawn.x,MAPS.throne.spawn.y,50));});
test('co-op claim actions require proximity, prevent duplicate starts, and snapshots include royal art',()=>{const w=new CoopWorld('firstfloor',configs,()=>.5),p=w.players[0];w.applyAction(p,{type:'royal',claim:'west',seq:1});assert.equal(w.claims.west,0);Object.assign(p,{x:CLAIMS[0].x,y:CLAIMS[0].y});w.applyAction(p,{type:'royal',claim:'west',seq:2});w.applyAction(p,{type:'royal',claim:'west',seq:3});assert.equal(w.enemies.filter(e=>e.royal==='west').length,1);const e=w.enemies.find(e=>e.royal==='west');assert.equal(w.snapshot().enemies.find(q=>q.id===e.id).royalArt,0);w.damage(e,1e9,p);assert.equal(w.claims.west,2);assert.ok(w.loot.some(l=>l.kind==='chest'));assert.ok(w.loot.some(l=>l.kind==='passive'));assert.ok(validSnapshot(w.snapshot()));});
test('final ascent keeps both builds and health, but resets section totals and preparation draft',()=>{const w=new CoopWorld('firstfloor',configs,()=>.5);w.claims={...createClaims(),west:2,east:2,tome:2,champion:2};const at=w.travelDestination().at;for(const p of w.players){p.x=at.x;p.y=at.y;p.inv={...p.inv,wand:8};p.level=30;p.hp=40;p.xp=7;}w.applyAction(w.players[0],{type:'travel',seq:1});for(const p of w.players)w.applyAction(p,{type:'travel_confirm',travel:1,seq:2});assert.equal(w.transition.phase,'comic');for(const p of w.players)w.applyAction(p,{type:'travel_skip',travel:1,seq:3});assert.equal(w.transition.phase,'prepare');for(const p of w.players)w.applyAction(p,{type:'travel_prepared',travel:1,seq:4,config:{bonuses:{}}});assert.ok(w.advanceStage());for(const p of w.players){assert.equal(p.level,30);assert.equal(p.hp,40);assert.equal(p.inv.wand,8);assert.equal(p.xp,7);}assert.equal(w.map.id,'throne');assert.equal(w.gold,0);assert.equal(w.time,0);assert.equal(w.enemies.length,15);});
test('royal charge is telegraphed before dash; king death ends party with victory',()=>{const e={royalArt:2,x:0,y:0,hp:100,maxHp:100,damage:20,royalCast:0},p={x:200,y:0};let moved=0;const api={move:()=>moved++,ring:()=>{},bolt:()=>{}};royalCombat(e,p,.05,api);assert.equal(moved,0);assert.ok(e.charge.t>0);for(let i=0;i<20;i++)royalCombat(e,p,.05,api);assert.ok(moved>0);const w=new CoopWorld('throne',configs,()=>.5);const king=w.spawnRoyal(KING);w.damage(king,1e9,w.players[0]);assert.equal(w.over,true);assert.equal(w.victory,true);});

test('ward guidance includes every gate requirement and updates after banners',async()=>{
 const {wardSteps,stairHint,claimMarkers,wardBrief}=await import('../public/royal-objectives.mjs');
 const s=createClaims();assert.match(wardBrief(s),/then defeat the champion/);assert.equal(wardSteps(s).length,3);
 assert.ok(claimMarkers(s).filter(m=>m.id).every(m=>m.kind.startsWith('ward-')));
 claimDeath(s,'west');assert.match(stairHint(s),/Oath Ward/);claimDeath(s,'east');assert.doesNotMatch(stairHint(s),/Oath Ward/);
 for(let i=0;i<3;i++)claimDeath(s,'banner'+i);
 assert.match(wardSteps(s)[2].task,/First Blade/);assert.ok(claimMarkers(s).some(m=>m.id==='champion'&&!m.done));
 s.tome=2;claimDeath(s,'champion');assert.match(stairHint(s),/All wards broken/);assert.ok(wardSteps(s).every(w=>w.done));
});
