import test from 'node:test';
import assert from 'node:assert/strict';
import {rewardLabel,passiveDelta,equipmentPanel,sectionSummary,MAP_LEGEND} from '../public/ui-panels.mjs';
import {CHARACTERS} from '../public/characters.mjs';
import {canDiscard} from '../public/rules.mjs';
test('reward presentation distinguishes upgrades, mastery and transformations',()=>{assert.match(rewardLabel('wand',0),/NEW WEAPON/);assert.match(rewardLabel('wand',7),/MASTERY · 7 → 8/);assert.equal(rewardLabel('legion',1),'TRANSFORMATION');assert.match(passiveDelta('echo',{echo:7},CHARACTERS.knight,{}),/Extra projectiles 4 → 6/);assert.match(passiveDelta('hourglass',{hourglass:7},CHARACTERS.knight,{}),/Cooldown × 0.44 → 0.2/);});
test('build separates owned equipment and shared benefits without offering to discard ally items',()=>{const html=equipmentPanel({sword:1},id=>id,{capacity:4,charges:{banish:2},removable:canDiscard,attribute:'data-remove',shared:{echo:8}});assert.match(html,/Weapons/);assert.match(html,/Owned passives/);assert.match(html,/Shared by your ally/);assert(!html.includes('data-remove="echo"'));assert.match(html,/data-remove="sword" disabled/);});
test('section descriptions and map legend cover objectives and all pickup types',()=>{assert(!sectionSummary('firstfloor').includes('30-minute'));assert.match(sectionSummary('throne'),/Prepare your build/);for(const label of ['Chest','Boss','Healing','Passive relic','Coins','Parchment'])assert(MAP_LEGEND.includes(label));});

test('both profile retry controls work after a loading failure',async()=>{const oldFetch=globalThis.fetch;globalThis.fetch=async()=>({json:async()=>({owner:false})});try{const {mountStartMenu}=await import('../public/start-menu.mjs');let calls=0,retries=[];const root={set innerHTML(v){this.html=v;retries=Array.from(v.matchAll(/<button[^>]*data-retry/g),()=>({addEventListener(type,fn){this.click=fn;}}));},querySelector(){return null;},querySelectorAll(selector){return selector==='[data-retry]'?retries:[];}};mountStartMenu({root,active:()=>true,load:async()=>{calls++;throw new Error('Offline');}});await new Promise(r=>setTimeout(r,0));assert.equal(retries.length,2);assert(retries.every(b=>typeof b.click==='function'));await retries[1].click();assert.equal(calls,2);await retries[0].click();assert.equal(calls,3);}finally{globalThis.fetch=oldFetch;}});
